### ISSUE TITLE
Prompt the user to update the app

### ISSUE THREAD

**Issue by mstrk** [Cloudoki/appdoki-rn#15]
Eventually we are going to have conflicts between the api and the app version. Prompt the user to update the app in such cases.

We could do this in two ways:
 - We set up [remote config](https://rnfirebase.io/remote-config/usage) and update the versions in firebase console.
 - The API accepts an header with the client app version and throws a specific status code that we will only use in the app for such case.

Let's discuss this.

cc @s1moe2 @a31859

**Comment by s1moe2** [comment]
Using remote config sounds good. It stays in the app scope, and the app only needs to talk to firebase. Otherwise the API would: a) need be aware that the version is not the most recent; b) probably talk to firebase as well to get that info and, therefore, become a middleman.
Unless I'm not seeing this straight.

**Comment by mstrk** [comment]
No no, one or the other. But yeah remote config is a good option.

**Comment by mstrk** [comment]
Remote config it will be then.
